### ISSUE TITLE
[使用问题] ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by xmuyong** [PaddlePaddle/PaddleRec#252]
python -m pip install paddle-rec -i https://mirror.baidu.com/pypi/simple

Building wheels for collected packages: pathlib
  Building wheel for pathlib (setup.py) ... done
  Created wheel for pathlib: filename=pathlib-1.0.1-py3-none-any.whl size=14348 sha256=1a742bbaae9155c36eefeaa0b66852843bdb4242f4b650bb96cf9b7887819ff6
  Stored in directory: /home/work/.cache/pip/wheels/ea/c2/62/0ae2836c6f4c45d02165aa3ae1e864f91b774dadc8ec9ec3ee
Successfully built pathlib
Installing collected packages: astor, numpy, opencv-python, graphviz, objgraph, Pillow, pyparsing, kiwisolver, six, python-dateutil, cycler, matplotlib, decorator, protobuf, funcsigs, pathlib, click, joblib, tqdm, regex, nltk, PyYAML, rarfile, wcwidth, prettytable, idna, urllib3, chardet, requests, gast, scipy, paddlepaddle, paddle-rec
Successfully installed Pillow-8.0.1 PyYAML-5.3.1 astor-0.8.1 chardet-3.0.4 click-7.1.2 cycler-0.10.0 decorator-4.4.2 funcsigs-1.0.2 gast-0.3.3 graphviz-0.14.2 idna-2.10 joblib-0.17.0 kiwisolver-1.3.0 matplotlib-3.3.2 nltk-3.5 numpy-1.19.2 objgraph-3.5.0 opencv-python-4.2.0.32 paddle-rec-1.8.5.1 paddlepaddle-1.8.5 pathlib-1.0.1 prettytable-1.0.1 protobuf-3.13.0 pyparsing-2.4.7 python-dateutil-2.8.1 rarfile-4.0 regex-2020.10.23 requests-2.24.0 scipy-1.5.3 six-1.15.0 tqdm-4.51.0 urllib3-1.25.11 wcwidth-0.2.5

python
Python 3.7.9 (default, Aug 31 2020, 12:42:55)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
/home/work/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/core.py:194: UserWarning: Load /usr/lib64/libgomp.so.1 failed
  warnings.warn("Load {} failed".format(dso_absolute_path))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/__init__.py", line 37, in <module>
    import paddle.complex
  File "/home/work/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/complex/__init__.py", line 15, in <module>
    from . import tensor
  File "/home/work/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/complex/tensor/__init__.py", line 15, in <module>
    from . import math
  File "/home/work/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/complex/tensor/math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "/home/work/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "/home/work/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/home/work/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/work/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/core.py", line 273, in <module>
    raise e
  File "/home/work/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/core.py", line 243, in <module>
    from .core_avx import *
ImportError: dlopen: cannot load any more object with static TLS

【miniconda3 安装的 python3.7】

**Comment by gentelyang** [comment]
去掉https://mirror.baidu.com/pypi/simple，直接python -m pip install paddle-rec
