### ISSUE TITLE
static_ps_trainer.py is throwing an exception 

### ISSUE THREAD

**Issue by pawelpiotrowicz** [PaddlePaddle/PaddleRec#604]
My command line:
```
python -u ../../../../tools/static_ps_trainer.py -m benchmark.yaml -bf16=True

```
I have an error:

```
INFO:__main__:Run Worker Begin
Traceback (most recent call last):
  File "../../../../tools/static_ps_trainer.py", line 351, in <module>
    benchmark_main.run()
  File "../../../../tools/static_ps_trainer.py", line 81, in run
    self.run_worker()
  File "../../../../tools/static_ps_trainer.py", line 116, in run_worker
    self.model.optimizer.amp_init(self.exe.place)
AttributeError: 'SGDOptimizer' object has no attribute 'amp_init'
```

but .. If you use version below it works fine:

```
commit e8c61ec375c6d1407e7d74d75ecbe1e2bd1b68eb
Merge: e1224448 296a1ea9
Author: zhang wenhui <frankwhzhang@126.com>
Date:   Wed Oct 13 15:17:49 2021 +0800

    Merge pull request #568 from seemingwang/master
    
    fix name error

```

Details:
```
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux

```

**Comment by frankwhzhang** [comment]
您好 请问使用的paddle版本是什么

**Comment by pawelpiotrowicz** [comment]
@frankwhzhang   latest version

**Comment by yinhaofeng** [comment]
能描述运行具体的paddle版本吗？可以用paddle.__version__查看
