### ISSUE TITLE
AI Studio中mind模型inference_model_to_serving转换模型后使用client.predict预测报错

### ISSUE THREAD

**Issue by sjun** [PaddlePaddle/PaddleRec#737]
PaddlePaddle2.2.2\paddle-serving-client 0.8.3
1、在AI Studio中测试mind模型，在config.yaml中增加以下几行
 use_inference: True
 save_inference_feed_varnames: ['hist_item','seq_len']
 save_inference_fetch_varnames: ["softmax_with_cross_entropy_0.tmp_0"]
2、使用python -u tools/static_trainer.py -m models/recall/mind/config.yaml命令生成模型。
3、使用以下测试代码，serving转换之前生成的模型，再构造测试数据预测。
import os
import logging
import numpy as np
import paddle
import paddle_serving_client.io as serving_io
from paddle_serving_app.local_predict import LocalPredictor

def serving(model_path, epoch_id):
    serving_io.inference_model_to_serving(model_path+"/"+str(epoch_id),
                                          serving_server="serving_server",
                                          serving_client="serving_client",
                                          model_filename="rec_inference.pdmodel",
                                          params_filename="rec_inference.pdiparams")

def process_feed_dict(recall_result):
    dic = {"hist_item": [2805, 2573], "seq_len": [2]}
    for key in dic:
        dic[key] = np.array(dic[key]).astype(np.int64).reshape(len(dic[key]), 1)
    return dic

def rank_predict(recall_result):
    client = LocalPredictor()
    client.load_model_config("serving_server")
    dict = process_feed_dict(None)
    print(dict)
    fetch_map = client.predict(feed=dict, fetch=["save_infer_model/scale_0.tmp_1"], batch=True)
    return fetch_map

if __name__ == "__main__":
    model_path = "output_model_mind"
    epoch_id = 0
    # serving(model_path, epoch_id)
    fetch_map = rank_predict(None)
    print(fetch_map)
    for i in range(1):
        list = fetch_map["save_infer_model/scale_0.tmp_1"].tolist()[i]
        print(list)
        list1 = fetch_map["save_infer_model/scale_0.tmp_1"][i][1]
        print("cell"+str(i)+"="+str(list1))

错误如下：
{'hist_item': array([[2805],
       [2573]]), 'seq_len': array([[2]])}
Traceback (most recent call last):
  File "predict.py", line 36, in <module>
    fetch_map = rank_predict(None)
  File "predict.py", line 28, in rank_predict
    fetch_map = client.predict(feed=dict, fetch=["save_infer_model/scale_0.tmp_1"], batch=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_app/local_predict.py", line 393, in predict
    self.predictor.run()
ValueError: In user code:

    File "tools/static_trainer.py", line 296, in <module>
      main(args)
    File "tools/static_trainer.py", line 69, in main
      fetch_vars = static_model_class.net(input_data)
    File "/home/aistudio/PaddleRec/models/recall/mind/static_model.py", line 78, in net
      hist_item, seqlen, labels)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/aistudio/PaddleRec/models/recall/mind/net.py", line 287, in forward
      seqlen)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/aistudio/PaddleRec/models/recall/mind/net.py", line 197, in forward
      B_mask = paddle.where(mask, B, pad)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/search.py", line 532, in where
      outputs={'Out': [out]})
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The dims of Inputs(Condition) and Inputs(X) should be same. But received Condition's shape is [1, 4, 20], X's shape is [2, 4, 20]
      [Hint: Expected cond_dims == x_dims, but received cond_dims:1, 4, 20 != x_dims:2, 4, 20.] (at /paddle/paddle/fluid/operators/where_op.cc:38)
      [operator < where > error]
不知是构造测试数据有错还是框架本身的原因？

**Comment by yinhaofeng** [comment]
根据报错，是在测试的时候paddle.where参数的输入出现问题。您可以尝试分析一下模型的shape和预测的shape的差别进行调整

**Comment by sjun** [comment]
安装您的提示重新调整了预测的shape，代码如下：
def hash2(a):
    return hash(a) % 600000

def process_feed_dict(recall_result):
    hist_item = [234, 3210, 3100, 2100, 3412, 2100, 4339, 3210, 3100, 2100, 3412, 2100, 4339, 3210, 3100, 2100, 3412, 2100, 4339, 3210]
    dic = {"hist_item": [], "seq_len": []}
    dic["hist_item"].extend([hash2(x) for x in hist_item])
    dic["seq_len"].append(hash2(20))
    dic["hist_item"] = np.array(dic["hist_item"]).astype(np.int64).reshape(-1, 20)
    dic["seq_len"] = np.array(dic["seq_len"]).astype(np.int64).reshape(-1, 1)
    return dic
不报上面的dims不相等问题了，但又报出了以下错误
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/input.py", line 223, in embedding
      'padding_idx': padding_idx
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Tensor not initialized yet when Tensor::type() is called.
      [Hint: holder_ should not be null.] (at /paddle/paddle/fluid/framework/tensor.h:218)
      [operator < lookup_table_v2 > error]
