### ISSUE TITLE
无法可视化梯度：参数的梯度是None

### ISSUE THREAD

**Issue by Waterkin** [PaddlePaddle/PaddleRec#846]
代码：
```
loss.backward(retain_graph=True)
optimizer.step()
for name, param in dy_model.named_parameters():
                if param.grad is not None:
                # [499, 117]
                    tag_name = "train/" + name + '/grad1'
                    log_visual.add_histogram(
                                tag=tag_name, 
                                values= param.grad.numpy(),
                                step=step_num,)
optimizer.clear_grad()
```

报错消息：
```
Warning:
tensor.grad will return the tensor value of the gradient. This is an incompatible upgrade for tensor.grad API.  It's return type changes from numpy.ndarray in version 2.0 to paddle.Tensor in version 2.1.0.  If you want to get the numpy value of the gradient, you can use :code:`x.grad.numpy()` 
  warnings.warn(warning_msg)
../../../tools/trainer.py:50: RuntimeWarning: divide by zero encountered in true_divide
  similiarity = np.dot(a, b.T)/(a_norm * b_norm)
../../../tools/trainer.py:50: RuntimeWarning: invalid value encountered in true_divide
  similiarity = np.dot(a, b.T)/(a_norm * b_norm)
Traceback (most recent call last):
  File "../../../tools/trainer.py", line 284, in <module>
    main(args)
  File "../../../tools/trainer.py", line 204, in main
    step=step_num,)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/visualdl/writer/writer.py", line 435, in add_histogram
    hist, bin_edges = np.histogram(values, bins=buckets)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/histograms.py", line 780, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/histograms.py", line 417, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/histograms.py", line 315, in _get_outer_edges
    "autodetected range of [{}, {}] is not finite".format(first_edge, last_edge))
ValueError: autodetected range of [nan, nan] is not finite
```
求大神帮忙，蟹蟹！

**Comment by wangzhen38** [comment]
你是想打印训练过程中的参数梯度？

**Comment by Waterkin** [comment]
> 你是想打印训练过程中的参数梯度？

是的

**Comment by wangzhen38** [comment]
`for param in model.parameters():
		if param.grad is None:
		continue
		import numpy as np
		print(param.name,
		      param.numpy().sum(), param.grad.numpy().sum())`
可以参考线这个

**Comment by Waterkin** [comment]
> for param in model.parameters(): if param.grad is None: continue import numpy as np print(param.name, param.numpy().sum(), param.grad.numpy().sum())
> 
> 可以参考下这个

谢谢你！成功解决！
