### ISSUE TITLE
TDM模型快速开始部分运行失败: KeyError: '102489422'

### ISSUE THREAD

**Issue by Jim59-Chen** [PaddlePaddle/PaddleRec#863]
@wangzhen38  我尝试参照README.md的教程运行实例，我使用的版本是stable 2.3，在参考[快速开始](https://github.com/PaddlePaddle/PaddleRec/tree/release/2.3.0/models/treebased#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)部分运行时出现错误。我成功地完成了初次训练，并聚类生成树，但是当我再次完成训练(Step 2)后，却无法成功进行预测。报错如下：
```python
Traceback (most recent call last):
  File "infer.py", line 295, in <module>
    first_layer_set, config)
  File "infer.py", line 210, in infer
    for groudtruth, user_input in reader():
  File "infer.py", line 60, in reader
    groudtruth, output_list = self.line_process(line)
  File "infer.py", line 49, in line_process
    bidword_list = [self.id_code[s] for s in bidword_list]
  File "infer.py", line 49, in <listcomp>
    bidword_list = [self.id_code[s] for s in bidword_list]
KeyError: '102489422'
```
经过调试，我发现再次建树生成的ids_id.txt与初次建树生成文件的key字段完全不一样，它们之间相差非常大。
![Snipaste_2022-12-25_19-51-17](https://user-images.githubusercontent.com/102496108/209466850-31634c45-2416-4869-8abd-cf116cebd3f3.png)

同时再次建树生成ids_id.txt中所有的id在 [测试数据](https://github.com/PaddlePaddle/PaddleRec/blob/release/2.3.0/models/treebased/data/demo_test_data/test_data)都不存在，正因如此才会出现KeyError。我确实不太清楚是哪一步出现了问题，感觉可能是生成的`epoch_0_item_embedding.txt` 的id号和原始数据对不上。 @wangzhen38  我是哪一步弄错了吗？

**Comment by wangzhen38** [comment]
稍等，我复现下

**Comment by wangzhen38** [comment]
你可以cherry pick下这个pr再试下，https://github.com/PaddlePaddle/PaddleRec/pull/864

**Comment by Jim59-Chen** [comment]
您的意思是让我在v2.3.0的基础上cherry pick这个Pull Request?

**Comment by Jim59-Chen** [comment]
@wangzhen38 感谢您百忙之中抽空来解决这一Issue, 但我依旧没能成功按照[快速开始](https://github.com/PaddlePaddle/PaddleRec/tree/release/2.3.0/models/treebased#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B) 完成复现。
我使用Paddle 2.4.0, 将您的PR新增到master分支上，在第二次执行训练的时候报了相同的错误: KeyError. 
![master-fix-tdm](https://user-images.githubusercontent.com/102496108/209663042-c53ce67a-d739-4195-830c-bd35fadb47ab.png)
我粗略检查，Paddle 2.4.0并没有对应方法，能说明一下使用的Paddle环境吗？

仔细分析您的fix-tdm，似乎没有完全解决问题，按照我对代码的理解，建树时的输入文件(item_mini.txt, epoch_0_item_embedding.txt)应当包含**item_id**, **embedding**，而在提取叶子节点的embedding时(Step4) 
[get_leaf_embedding.py](https://github.com/PaddlePaddle/PaddleRec/blob/release/2.3.0/models/treebased/tdm/get_leaf_embedding.py)是将每个叶子节点的的序号和对应**embedding**写入，而将叶子节点对应的item_id给丢弃，这就导致了再次建树时出现一点小错误。具体来说是这段代码

![Snipaste_2022-12-27_20-16-11](https://user-images.githubusercontent.com/102496108/209665457-68d94bf5-03d9-47a6-b0cc-6f9cd8e87244.png)

**Comment by Jim59-Chen** [comment]
我尝试基于release/2.3.0和 #864的基础上，继续如下改动：
- 通过读取 ../builder/ids_id.txt文件获取node_id到item_id的映射关系
- 将item_id和对应embedding写入输出文件（如下图所示），在此之后，成功复现[快速开始](https://github.com/PaddlePaddle/PaddleRec/tree/release/2.3.0/models/treebased#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)部分。
![final_fix](https://user-images.githubusercontent.com/102496108/209743436-380eeb3f-8278-4ddd-82f5-17d4aabaf4db.png)

**Comment by wangzhen38** [comment]
1. paddle2.4的报错问题属于版本更新的原因，已经提pr修复
2. 保存emb那里确实遗漏了id转换逻辑，也提了修复pr
多谢关注，有其他问题欢迎随时交流～
