### ISSUE TITLE
静态图模型能否修改共享参数形状

### ISSUE THREAD

**Issue by arbitraryking** [PaddlePaddle/PaddleRec#920]
我想共享embedding层和最后输出fc层的参数，但是两个shape不同，embedding的shape是[65555,256],fc的weight是[256,65555],需要将embedding做下转置，没有找到对应的API。网上有推荐用动态图的，我想知道静态图有解决方法吗？
```
shared_param_attrs = fluid.ParamAttr(name="programset_embedding",initializer=paddle.nn.initializer.Uniform())

emb = paddle.static.nn.sparse_embedding(
                    input=input[1],
                    size=[
                        self.sparse_feature_number[i]+1, self.sparse_feature_dim[i]
                    ],
                    param_attr=paddle.ParamAttr(
                        name="SparseFeatFactors",
                        initializer=paddle.nn.initializer.Uniform()))
...
final_layer = paddle.static.nn.fc(
                x=cust_embdding,
                size=65555,
                weight_attr=shared_param_attrs)
```

Traceback (most recent call last):
  File "tools/static_trainer.py", line 315, in <module>
    main(args)
  File "tools/static_trainer.py", line 69, in main
    fetch_vars = static_model_class.net(input_data)
  File "[E:\PaddleRec\PaddleRec\models\recall\ha_youtube_dnn\static_model.py](file:///E:/PaddleRec/PaddleRec/models/recall/ha_youtube_dnn/static_model.py)", line 110, in net
    weight_attr=shared_param_attrs)
  File "[d:\Anaconda\envs\py37\lib\site-packages\decorator.py](file:///D:/Anaconda/envs/py37/lib/site-packages/decorator.py)", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "[d:\Anaconda\envs\py37\lib\site-packages\paddle\fluid\wrapped_decorator.py](file:///D:/Anaconda/envs/py37/lib/site-packages/paddle/fluid/wrapped_decorator.py)", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "[d:\Anaconda\envs\py37\lib\site-packages\paddle\fluid\framework.py](file:///D:/Anaconda/envs/py37/lib/site-packages/paddle/fluid/framework.py)", line 558, in __impl__
    return func(*args, **kwargs)
  File "[d:\Anaconda\envs\py37\lib\site-packages\paddle\static\nn\common.py](file:///D:/Anaconda/envs/py37/lib/site-packages/paddle/static/nn/common.py)", line 166, in fc
    name=name,
  File "[d:\Anaconda\envs\py37\lib\site-packages\paddle\fluid\layers\nn.py](file:///D:/Anaconda/envs/py37/lib/site-packages/paddle/fluid/layers/nn.py)", line 398, in fc
    attr=param_attr, shape=param_shape, dtype=dtype, is_bias=False
  File "[d:\Anaconda\envs\py37\lib\site-packages\paddle\fluid\layer_helper_base.py](file:///D:/Anaconda/envs/py37/lib/site-packages/paddle/fluid/layer_helper_base.py)", line 385, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "[d:\Anaconda\envs\py37\lib\site-packages\paddle\fluid\framework.py](file:///D:/Anaconda/envs/py37/lib/site-packages/paddle/fluid/framework.py)", line 3953, in create_parameter
    param = Parameter(global_block, *args, **kwargs)
  File "[d:\Anaconda\envs\py37\lib\site-packages\paddle\fluid\framework.py](file:///D:/Anaconda/envs/py37/lib/site-packages/paddle/fluid/framework.py)", line 6926, in __init__
    **kwargs
  File "[d:\Anaconda\envs\py37\lib\site-packages\paddle\fluid\framework.py](file:///D:/Anaconda/envs/py37/lib/site-packages/paddle/fluid/framework.py)", line 1461, in __init__
    "matched.".format(self.name, old_shape, shape)
ValueError: Variable 'programset_embedding' has been created before. The previous shape is (65345, 256), the new shape is (256, 65345). They are not matched.

**Comment by wangzhen38** [comment]
可以参考下这个，https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/transpose_cn.html#transpose

**Comment by arbitraryking** [comment]
找到了相关API，静态图中参数都是Variable类型，但好像没有能通过Variable name直接拿到的API，我现在只能迭代所有Variable找到需要的然后取出它
```
prog = paddle.static.default_main_program()
final_layer_v = None
for i in prog.list_vars():
    if i.name=="SparseFeatFactors0":
    final_layer_v = i
    break
output = paddle.fluid.layers.matmul(cust_embedding,final_layer_v,transpose_y=True)
```

**Comment by arbitraryking** [comment]
> 可以参考下这个，https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/transpose_cn.html#transpose 如果满足不了需求，可以去paddle主repo上提issue哈，https://github.com/PaddlePaddle/Paddle/issues

最开始我试的的就是这个API,需要传入Tensor类型，动态图模型应该可以用，静态图里都是Variable
