### ISSUE TITLE
module 'paddle' has no attribute 'is_compiled_with_custom_device'

### ISSUE THREAD

**Issue by Dominic-ZZ** [PaddlePaddle/PaddleRec#926]
```
λ 5fd09798794c /code/PaddleRec python -u ./tools/trainer.py -m ./models/rank/dlrm/config.yaml # 全量数据运行config_bigdata.yaml
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
2023-05-17 03:30:32,956 - INFO - **************common.configs**********
2023-05-17 03:30:32,956 - INFO - use_gpu: True, use_xpu: False, use_npu: False, use_visual: False, train_batch_size: 2, train_data_dir: data/sample_data/train, epochs: 3, print_interval: 2, model_save_path: output_model_dlrm
2023-05-17 03:30:32,956 - INFO - **************common.configs**********
W0517 03:30:32.957670  1244 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.2
W0517 03:30:32.962177  1244 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
Traceback (most recent call last):
  File "./tools/trainer.py", line 227, in <module>
    main(args)
  File "./tools/trainer.py", line 98, in main
    dy_model = dy_model_class.create_model(config)
  File "/code/PaddleRec/models/rank/dlrm/dygraph_model.py", line 41, in create_model
    self_interaction=False)
  File "/code/PaddleRec/models/rank/dlrm/net.py", line 65, in __init__
    if paddle.is_compiled_with_custom_device('npu'):
AttributeError: module 'paddle' has no attribute 'is_compiled_with_custom_device'
```
Paddle版本：(Docker: registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8)
```
PaddlePaddle 2.3.2.post112, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON
```

**Comment by wangzhen38** [comment]
这个需要安装最新的包，或者不是npu设备的话，可以先将报错语句注释掉

**Comment by wml1993** [comment]
那什么版本的paddle 需要呢？ 我已经是2.4.2

**Comment by wangzhen38** [comment]
2.4不行，应该需要拉取develop分支自己编译

**Comment by huzuoliang** [comment]
安装2.5.0版本就不会报这个错误了
